from gym_maze.envs.abstract_maze import AbstractMaze
from gym_maze.envs.MazeF1 import MazeF1
from gym_maze.envs.MazeF2 import MazeF2
from gym_maze.envs.MazeF3 import MazeF3
from gym_maze.envs.MazeF4 import MazeF4
from gym_maze.envs.Maze4 import Maze4
from gym_maze.envs.Maze5 import Maze5
from gym_maze.envs.Maze6 import Maze6
from gym_maze.envs.BMaze4 import BMaze4
from gym_maze.envs.Woods1 import Woods1
from gym_maze.envs.Woods14 import Woods14
